### ISSUE TITLE
English documentation?

### ISSUE THREAD

**Issue by stuta** [halower/vue-tree#10]
Looks good, can we get english documentation?

**Comment by halower** [comment]
english documentation should be available this weekend

**Comment by ReynerHL** [comment]
It really looks awesome!! It is a shame we can't work better with it because the language. Any progress with this? I'm pretty sure the community will glad you choose english for the documentation.

**Comment by halower** [comment]
sorry, we've been a little busy lately. we'll try our best to do it, u can try use google translation

**Comment by halower** [comment]
https://github.com/halower/vue-tree/blob/master/README.md
