### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by stuta** [halower/vue-tree#11]
I add: "vue-tree": "*" to my package.json. Result is vue-tree -folder with only package.json:
{
  "name": "vue-tree",
  "version": "1.0.0",
  "description": "vue tree",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/zhaotoday"
  },
  "keywords": [
    "vue",
    "tree"
  ],
  "author": "zhaojintian",
  "license": "ISC"
}

**Comment by halower** [comment]
没有发布到npm 仓库

**Comment by halower** [comment]
npm install vue2-tree
