### ISSUE TITLE
强烈建议添加最内层不可展开（展开位不显示）选项。

### ISSUE THREAD

**Issue by sanriqing** [halower/vue-tree#110]

**Comment by sanriqing** [comment]
看了源代码tree li根据 !item.parent || this.hasChildren || item.async 条件判断，但是parent 这个props 却没有在treeui中传下来。所以parent永远都是空。所以一只都在，望解决

**Comment by CosSalt** [comment]
你的问题是当树只存在一层时，依旧会存在展开按钮？

**Comment by emilyzhao21** [comment]
同样遇到了这个问题，如何解决呢？

**Comment by emilyzhao21** [comment]
发送自 Windows 10 版邮件应用

发件人: CosSalt
发送时间: 2018年9月7日 0:23
收件人: halower/vue-tree
抄送: Emily; Comment
主题: Re: [halower/vue-tree] 强烈建议添加最内层不可展开（展开位不显示）选项。 (#110)

能不能发个截图，并标注一下问题

**Comment by emilyzhao21** [comment]
好的，谢谢，我试一下

**Comment by CosSalt** [comment]
@sanriqing @emilyzhao21 新增了一个topMustExpand配置项,设为false可以解决你们的问题
