### ISSUE TITLE
啥时候能出反向赋值的功能啊。。。通过已被选中的节点数组，渲染节点树的样式现在不能做到吧？

### ISSUE THREAD

**Issue by imyoursazhou** [halower/vue-tree#111]
现在获取已选中的节点数组什么的都很方便，就是功能需求里还有个编辑，就是要把已选中的项赋值到节点树中，并展开相应的样式，现在只能通过this.$refs.tree.nodeSelected(node);设置单个节点的选中状态，但是父节点的状态就没办法改变了

**Comment by halower** [comment]
请关注下最下边的二维码，就有动力了

**Comment by CosSalt** [comment]
@imyoursazhou 现在可以通过设置allowGetParentNode为true,然后通过节点的parent方法拿到父节点,顶层节点的父节点会返回null
