### ISSUE TITLE
没有子节点的时候为何前面会有+号

### ISSUE THREAD

**Issue by liub1934** [halower/vue-tree#115]
数据用的例子里面的默认的
![image](https://user-images.githubusercontent.com/29849550/45273605-068a3a00-b4e6-11e8-98ce-d3d4eb851fd0.png)

![image](https://user-images.githubusercontent.com/29849550/45273583-f5d9c400-b4e5-11e8-8475-220e7e1fa34b.png)

![image](https://user-images.githubusercontent.com/29849550/45273573-ebb7c580-b4e5-11e8-9b9f-cb55cc97a58f.png)

**Comment by Ghjsw** [comment]
同问这个

**Comment by liub1934** [comment]
@Ghjsw 
鬼知道什么问题 作者没个回复就关掉了 是我太菜 还是你太吊了 都不带回复的，弃之用这个了https://github.com/zdy1988/vue-jstree
