### ISSUE TITLE
请问，筛选后点击一级节点，不显示的节点为什么也获取了？如下图

### ISSUE THREAD

**Issue by huodaokai** [halower/vue-tree#121]
![image](https://user-images.githubusercontent.com/24378619/46198330-c842a680-c33e-11e8-8eff-a49bbfe16904.png)
使用getCheckedNodes()方法获取的，点击一级节点如何只获取搜索后的节点？
谢谢！

**Comment by CosSalt** [comment]
@huodaokai 你是想获取搜索到的节点？可以用getNodes方法来自定义获取，getNodes({searched: true}, nodes, true)

**Comment by huodaokai** [comment]
@CosSalt 我是要筛选过后打钩的节点，但是我使用getCheckedNodes（），点击一级节点获取的是所有的节点，并不是筛选后的5个节点，点击其他节点获取是正确的，getSelectedNodes这个方法我没获取到。

**Comment by CosSalt** [comment]
@huodaokai ok,明白你意思了，这个目前确实没处理好，晚上回去改一下，目前的解决思路是getCheckedNodes添加一个参数，用于判断是否会获取已隐藏节点

**Comment by huodaokai** [comment]
@CosSalt 恩，辛苦
