### ISSUE TITLE
树懒加载，设置node.expanded=true节点没有展开加载数据

### ISSUE THREAD

**Issue by ronniesir** [halower/vue-tree#124]
1.树懒加载，设置node.expanded=true
2.前方图标显示展开但节点没有展开加载数据
![image](https://user-images.githubusercontent.com/3816871/47026561-5076d780-d198-11e8-8783-4da3d3190564.png)

![image](https://user-images.githubusercontent.com/3816871/47026545-4654d900-d198-11e8-926e-f8ad8b3cf7ff.png)

**Comment by CosSalt** [comment]
expanded是用来表示时候展开，本质上与加载数据没有一点关系，如果你需要你需要自己实现为节点添加子节点的逻辑
在demo中，可以这样实现
```vue
if ( v ) {
  console.log(node)
  this.$set(node, 'expanded', v)
  this.asyncLoad2(node)
 }
```
