### ISSUE TITLE
multiple 设置false后，只是去掉复习框的框框，但是还是可以通过鼠标进行多选

### ISSUE THREAD

**Issue by chend1005** [halower/vue-tree#126]

**Comment by CosSalt** [comment]
你是指checked属性发生了改变？

**Comment by bundery** [comment]
同样遇到了这个问题，子节点还是多个多选

**Comment by Ghjsw** [comment]
1.7.5的这个问题还是存在啊

**Comment by Ghjsw** [comment]
![image](https://user-images.githubusercontent.com/20982392/48053796-84b54500-e1e6-11e8-9998-055973497478.png)
设置了单选,但还是可以用鼠标多选
