### ISSUE TITLE
能否设置某各节点不能被选中啊

### ISSUE THREAD

**Issue by chend1005** [halower/vue-tree#127]

**Comment by CosSalt** [comment]
之后可以增加

**Comment by CosSalt** [comment]
@chend1005 ，你也可以自己处理，截图是demo里面的，你可以看一下
![g7pzl2 s j cvv hksxy kd](https://user-images.githubusercontent.com/36765589/47954619-e303dd00-dfc6-11e8-8c82-9c4af3394d51.png)
