### ISSUE TITLE
:multiple="false"时,元素还是可以多选,请问可以单选吗

### ISSUE THREAD

**Issue by Ghjsw** [halower/vue-tree#138]

**Comment by Ghjsw** [comment]
![image](https://user-images.githubusercontent.com/20982392/48053849-a57d9a80-e1e6-11e8-8680-6247d589f460.png)

设置了单选,但还是可以用鼠标多选

**Comment by Ghjsw** [comment]
t-vue-tree

**Comment by CosSalt** [comment]
最新的可以，等发布之后可以使用

**Comment by David-Tsui** [comment]
請問何時發布? 當前npm上1.7.8依然有此問題

**Comment by halower** [comment]
这个应该修复了啊，是不是你的node_moudles没有卸载干净

**Comment by halower** [comment]
好的，周末我们在测试一下，争取周末修复

**Comment by halower** [comment]
好的，周末我们在测试一下，争取周末修复

**Comment by David-Tsui** [comment]
好的，麻煩了，因為單/多選bug在Tree component是不容許存在的。
我個人也是vue jsx愛用者，所以才會選此。
另外不知道是否有支援節點的 hover? 想要hover 節點時才顯示某些按鈕。

先謝謝您的回覆了

**Comment by halower** [comment]
是可以的，我们之前实现过右侧菜单，jsx是支持的

**Comment by CosSalt** [comment]
@David-Tsui 你是自定义的tpl吗？

**Comment by David-Tsui** [comment]
有試過，原本以為是自訂的問題，後來之前抓你們的基礎demo code來用，一樣是壞的
試過npm上 1.7.7, 1.7.8版本

**Comment by CosSalt** [comment]
@David-Tsui 你是想一次只能选一个元素吗？

**Comment by CosSalt** [comment]
@David-Tsui 
:multiple="false"是用来设置前面的checkox时候显示，如果想设置后面的文字单选就设置:radio='true'
