### ISSUE TITLE
Support for case insensitive search

### ISSUE THREAD

**Issue by joaossantos** [halower/vue-tree#143]
![image](https://user-images.githubusercontent.com/45002783/48548067-f4e95800-e8c3-11e8-9c54-cac614ae575b.png)

---

![image](https://user-images.githubusercontent.com/45002783/48548550-27478500-e8c5-11e8-9674-327548cca0dc.png)

I would like to have an option so that the images above return the same search results.
Thanks in advance

**Comment by halower** [comment]
This is because the query node uses the```IndexOf ```method, it is a fuzzy filtering method, your requirements are accurate query, the next Monday version will provide a configuration parameter to determine whether it is accurate query, thank you for your feedback

**Comment by joaossantos** [comment]
Thanks for the quick answer.

I tried this but it's still not working properly

![v](https://user-images.githubusercontent.com/45002783/48571660-6397d700-e8ff-11e8-90e7-726756c6ae32.png)

Any idea?

**Comment by CosSalt** [comment]
@joaossantos
![image](https://user-images.githubusercontent.com/36765589/48623547-efcffa00-e9e4-11e8-9dc2-28b695db80c8.png)
```vue
search () {
      this.$refs.tree1.searchNodes(node =>new RegExp(this.searchword, 'i').test(node.title))
    }
```

**Comment by srikanth2042** [comment]
@halower how do I enable case insensitive search option on the search box that comes pre-loaded with the plugin?
![image](https://user-images.githubusercontent.com/33093586/65664392-dc56dc00-e056-11e9-8d83-3a57dbdd176a.png)

**Comment by srikanth2042** [comment]
@halower can you elaborate bit more, How do I bind the `searchNodes` method to inbuilt search box in the plugin? I wish there could be boolean flag `searchcaseinsensitive` that turns on the case insensitive search (the way most search operations works) from v-select-tree plugin itself.

**Comment by halower** [comment]
I'll reply to the example later, it's going to be a little busy

**Comment by halower** [comment]
```
export default {
data () {
  return {
     ...
      searchword: ''
  }
},
  ...
   search (searchcaseinsensitive) {
      this.$refs.tree1.searchNodes(node =>new RegExp(this.searchword, searchcaseinsensitive ?'i' : null).test(node.title))
    }
}
```

**Comment by srikanth2042** [comment]
To put it more straightforward, I have got the following code written in vue-cli with typescript:
```
<template>
  <div>
    <v-select-tree ref='tree' :data="treeData" :multiple="true" :v-model="['node-1-2']"/>
  </div>
</template>

<script lang="tsx">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class Home extends Vue {
  protected searchword = '';
  protected treeData: any = [{
    title: 'node1',
    expanded: true,
    children: [{
      title: 'node 1-1',
      expanded: true,
      children: [{
        title: 'node 1-1-1'
      }, {
        title: 'node 1-1-2'
      }, {
        title: 'node 1-1-3'
      }]
    }, {
      title: 'node 1-2',
      children: [{
        title: "<span style='color: red'>node 1-2-1</span>"
      }, {
        title: "<span style='color: red'>node 1-2-2</span>"
      }]
    }]
  }];

  public search () {
    this.$refs.tree.searchNodes((node : any) =>new RegExp(this.searchword).test(node.title));
  }
}
</script>
```
And it is rendering me following tree:
![image](https://user-images.githubusercontent.com/33093586/65716351-99c7ea80-e0bc-11e9-952d-b54b47afbe07.png)
@halower Now I am not sure how to bind `search()` function with `<v-select-tree ref='tree' :data="treeData" :multiple="true" :v-model="['node-1-2']"/>`
