### ISSUE TITLE
VSelectTree

### ISSUE THREAD

**Issue by fgsdfger** [halower/vue-tree#146]
在使用v-select-tree标签的时候，调用addNodes(),addNOde()等方法时出错
`TypeError: "_this.$refs.tree.addNodes is not a function"`
html:
` <v-select-tree ref="tree"  :data="groupTree"  @async-load-nodes="async"></v-select-tree>`
js:
` this.$set(node, 'loading', true)`
`                axios.post("/group/queryGroup",qs.stringify({`
`                    id:node.id`
`                })).then((data)=> {`
`                    console.log(this.$refs.tree.getNodes);`
`                    this.$refs['tree'].addNodes(node,data.data);`
`                    this.$set(node, 'loading', false)`
`                }).catch((error) =>{`
`                    console.log(error)`
`                })`

**Comment by CosSalt** [comment]
@fgsdfger 最新版，你在v-select-tree-select-tree中可以通过getTreeRef()方法拿到v-tree的ref
```vue
<v-select-tree ref='selectTree' />
const vTreeRef = this.refs.selectTree.getTreeRef()
vTreeRef .addNodes()
```

**Comment by halower** [comment]
长时间没有回复暂时关闭
