### ISSUE TITLE
取消选中应该执行的代码

### ISSUE THREAD

**Issue by betterRunner** [halower/vue-tree#164]
我想在代码层面取消选中所有nodes，但尝试了以下代码没有效果：
```
const selectedNode = this.$refs.tree1.getSelectedNodes()
for (const node of selectedNode) {
   this.$set(node, 'selected', false)
}
```
查看源码执行render的时候'selected'还是true，
请问正确更新node的'selected'状态应该是怎样的？
谢谢

**Comment by halower** [comment]
const selectedNode = this.$refs.tree1.getSelectedNodes(true),这段代码应该就有效了

**Comment by betterRunner** [comment]
@halower 抱歉没有认真看文档，设置了isOriginal=true就可以更改node属性了，谢谢~
