### ISSUE TITLE
vuecli3

### ISSUE THREAD

**Issue by mlinda** [halower/vue-tree#167]
vuecli3 是按demo走的代码，使用自定义的tpl报错是Duplicate declaration "h"，因为要添加点击节点加载数据

**Comment by halower** [comment]
应该是配置问题，你可以运行demo或者进群提问

**Comment by mlinda** [comment]
卸载重新安装，eslint检测有错不过可以用了；

**Comment by mlinda** [comment]
还有个问题想问下，初始选中 initSelected  不起作用，初始时给对象添加checked也没有效果，selected有效果，但是我把点击node title 的方法 tpl自定义为加载子节点了，这个怎么解决

**Comment by mlinda** [comment]
群名是多少，我进群把

**Comment by halower** [comment]
文档里面最上边有

**Comment by mlinda** [comment]
好吧，估计是有延迟，我再看下，谢了
