### ISSUE TITLE
勾选框checked的值与勾选状态不匹配

### ISSUE THREAD

**Issue by LeasonX** [halower/vue-tree#175]
当初始化:data时，设置node的checked属性，渲染出来的树对应的节点是勾选状态的，但是手动勾选就无响应，勾选可能生效了，但是勾选状态一直都是不改变的，这是不是一个大bug。

**Comment by halower** [comment]
你用this. $set就可以了，目前这块还是受限制之前vue对对象内部属性监控不到的特点，如果后面有机会会全部更新成Vue3的响应对象，就可以直接赋值了

**Comment by LeasonX** [comment]
ok了
