### ISSUE TITLE
Selecting all children is automatically selecting the parent when scoped set to true

### ISSUE THREAD

**Issue by srikanth2042** [halower/vue-tree#176]
@halower @ddtramp @CosSalt when I set the property `scoped=true`, the nodes in the tree are supposed to act independently i.e. selecting a parent node should not select all of its children automatically(it's working fine) and selecting all the children should not select its parent automatically(it's not working). Was this intentional or is it a bug? Can you fix this if this is a bug?

Example:
I selected node `node 1-1-1`:
![image](https://user-images.githubusercontent.com/33093586/66545396-3330db00-eb58-11e9-9fe1-75b457681e29.png)

And then, when I select the node `node 1-1-2` its automatically selecting the parent `node 1-1` which was not supposed to happen when scoped(=true) mode is on.
![image](https://user-images.githubusercontent.com/33093586/66545607-b18d7d00-eb58-11e9-8222-f28ce2c82e89.png)

**Comment by CosSalt** [comment]
it's a bug

**Comment by srikanth2042** [comment]
@CosSalt can we get this bug fixed? We are extensively using this plugin as it has excellent features. We'd love to see this plugin without bugs.

**Comment by CosSalt** [comment]
@srikanth2042 of course，I'm fixing it。

**Comment by CosSalt** [comment]
@srikanth2042 version 1.8.3 has fixed this bug

**Comment by srikanth2042** [comment]
Fix working perfectly, thanks @CosSalt

**Comment by amthekkel** [comment]
How does one initialise  pre selected checked items when using scoped=true.
when building the tree data without scoped=true, nodes can be checked/selected using the selected/checked properties. 
however, when using scoped=true, the required nodes aren't selected. Any suggestion?
![tree_node](https://user-images.githubusercontent.com/1446494/109705859-449bdc80-7bbe-11eb-8fd4-b76a275bc7df.png)
For this e.g., I would expect node-1-1-1 to be pre-selected. works without scoped property set, however, i need the ability to select parent without it selecting all leaf nodes, hence looking at the scoped property.
