### ISSUE TITLE
can change options dynamically

### ISSUE THREAD

**Issue by kpeng2016** [halower/vue-tree#33]
How can I real the function changing option dynamically,
the case is:
I have two button,
      one is a tree without any checkbox, another is a tree with checkbox,
and the options of showCheckbox I used is variable, after I click these two button alternately, I want to see the tree is with or without checkbox.
but I failed, is there any solution to solve it?

Thanks!

**Comment by halower** [comment]
The new version is coming soon, please wait

**Comment by halower** [comment]
because the options's type is Object ,you can use Vue.set to change options or try to use Object.assign

**Comment by halower** [comment]
the new version of the component is very easy to set up and you can look at
