### ISSUE TITLE
希望增加刷新树节点接口

### ISSUE THREAD

**Issue by wuchaohua** [halower/vue-tree#4]
组织机构删除一条记录，树节点不能同步刷新！

**Comment by halower** [comment]
好的，预计一周后会计划新增节点CRUD操作，这些都很容易可以通过tree-store自己扩展

**Comment by ddtramp** [comment]
/**
             * generate key 0-1-2-3
             * this is very important function for now module
             * @param treeData
             * @param parentKey
             * @returns {Array}
             */
            generateKey (treeData = [], parentKey) {
                treeData = treeData.map((item, i) => {
                    item.key = parentKey + '-' + i.toString();
                    return item;
                })
                return treeData;
            }

每一条数据都增加 一个 key 字段， 保存的是数据结构， 然后就可以任意操作 treeData 了；
只要可以 get 到操作数据的在 treeData 中的 position 就可以了
