### ISSUE TITLE
能不能添加demo在包里

### ISSUE THREAD

**Issue by IEfucker** [halower/vue-tree#42]
直接看到效果，安装babel报错了

**Comment by halower** [comment]
好的，我下午再发布一版带demo的包

**Comment by IEfucker** [comment]
感谢这么快的回复，能不能请教下，最近项目想用vue迭代，之前的ztree想换掉，虽然vue和jQ+ztree混用也可以，但不知道在你这个项目上做扩展怎么弄，好不好做。因为有些右键，一个option多个状态（除checkbox选中还有其他状态图标）需要做。还是说方案应该保守点，还是用ztree，能不能推荐下

**Comment by halower** [comment]
我的每个叶子选项都是支持自定义的，至于使用者怎么写我不关心，同时支持各个节点的却别定义我会把当前节点的上下文等信息传递过来，这也是我不选用slot插槽而选用jsx方式的原因，中午我会扩展两个事件，单击节点事件和复选框改变状态事件，同时更新到npm包中，再把样式分离出来，方便用户自定义样式。不知道是不是你想要的答案。 ps：请关注文档最下方，O(∩_∩)O哈哈~

**Comment by IEfucker** [comment]
很棒，期待你的更新，确实很给力，extend的方式如果有些帮助文档就更好了，明天和项目组多要点经费支持作者
