### ISSUE TITLE
how can i change it get children when expand?

### ISSUE THREAD

**Issue by Glenfiddish** [halower/vue-tree#45]
lazy load children when expand

**Comment by halower** [comment]
this.$set(node, 'expanded', true)

**Comment by Glenfiddish** [comment]
i know it is expanded, but it seem that not suitable for sending ajax to get children, when it use in file explorer

**Comment by halower** [comment]
when u get a child node or even his descendants, can't you tell if the node is a parent node?  also this function is opened.

**Comment by halower** [comment]
QQ Group: 255965810
