### ISSUE TITLE
展开收缩的动画不合适

### ISSUE THREAD

**Issue by Weiyu-Chen** [halower/vue-tree#50]
现在的展开折叠动画是 渐变，
不大符合对于树的折叠切换，一般用展开折叠（手风琴）动画比较合适。

动画效果写在了`<style scoped>`里面，除了改源码，在外部修改它的动画很是麻烦。 

建议去掉渐变动画，或者暴露出自定义动画的接口

**Comment by halower** [comment]
你好，你能否进行下修改动画样式，因为我不是前端，所以css很鸡肋

**Comment by Weiyu-Chen** [comment]
好的，这几天抽时间提个PR
