### ISSUE TITLE
Can not capture event async-load-nodes when there are more than three level.

### ISSUE THREAD

**Issue by nguyenquocthai94** [halower/vue-tree#61]
When create a tree with more than three level, it can not capture event async-load-nodes.
Cause : vm.$emit only trigger an event on the current instance.

**Comment by halower** [comment]
It is normal in the demo, and I will test the npm package later，thank you for your feedback.

**Comment by nguyenquocthai94** [comment]
i pulled source from git. and it is aslo not works.

**Comment by halower** [comment]
Hi! Can you please show a better example of your code, or provide an example repo? It's not clear what you're doing from the code you've provided.

**Comment by halower** [comment]
I'm sorry, I didn't notice this bug before. I misunderstood you, you can install vue-tree-halower@1.3.9, this version has fixed it
