### ISSUE TITLE
When you load new nodes via `asnync: true`, the child nodes' `asnync: true` does not have any effect

### ISSUE THREAD

**Issue by xavierpena** [halower/vue-tree#66]
That is to say:

- A node that is loaded asynchronously
- This node also has `async: true`
- The property will not have any effect: once we push "+" for this "newly loaded node", ` @async-load-nodes='asyncLoadNodes'` is not triggered.

**Comment by xavierpena** [comment]
I am banging my head against this one...

This is one of the things I have tried so far:

	response.json().then((nodes: Node[]) => { 
		for(let childNode of nodes)
			this.$emit('async-load-nodes', childNode);
		this.$refs.tree.addNodes(node, nodes);
	});

I have closely looked at [the code](https://github.com/halower/vue-tree/blob/master/src/components/tree.vue) and I can't figure out why the `async: true` property works only when the tree is loaded for the first time, and it doesn't when the node is added via `this.$refs.tree.addNodes(node, nodes);`.

If you have any hints, please let me know...

**Comment by xavierpena** [comment]
My dirty workaround:

1. Remove the `[+]` button:

    .halo-tree .tree-close {
        display: none !important;
    }
	
(I left the `[-]` button, because it is still useful)


2. Now that the `[+]` is out of the equation, forget about `@async-load-nodes="asyncLoadNodes"` and focus on `@node-click="nodeClick"`

3. This is my `nodeClick` function, which expands OR loads+expands depending on the node having `async: true` or `async: false`:

    async nodeClick(node: Node) {

        if (!node.nocheck)
            return;

        this.$set(node, 'expanded', !node.expanded);
        console.log(node.expanded);

        if (!node.async)
            return;

        this.$set(node, 'loading', true);

        fetch(node.query)
            .then((response) => {
                if (response.status != 200) {
                    let errorNode = this.getErrorNode("! Error loading the data... (" + response.status + " " + response.statusText + ")");
                    this.$set(node, 'children', [errorNode]);
                } else {
                    response.json().then((nodes: Node[]) => { 
                        this.$set(node, 'children', nodes);             
                    });
                }
                this.$set(node, 'loading', false);
            });
    }

**Comment by halower** [comment]
is it solved?

**Comment by xavierpena** [comment]
Not really, I just bent the library to provide a similar functionality that was good enough for my case.

It would be better to be able to use the [+] button (instead of clicking the node text) as intended by the library. It is not intuitive for the user to know that it must click the text, plus the information about "there are / there are not childnodes" is completely lost.

**Comment by halower** [comment]
ok,I'll see this issue

**Comment by halower** [comment]
the effect you want is not the Default mode in http://120.77.84.4/, use the + button

**Comment by halower** [comment]
I think I may not be the same as you think，async-load-nodes 是tree抛出来，你要在外层监听的事件，树会传递一个当前你要添加节点的目标节点（也就是新节点的父节点），你可以操作这个node参数，为他添加自己的子节点，而不是在你的子节点$emit("async-load-nodes")

**Comment by halower** [comment]
I have fixed this error, and later check the requirements of other users feedback, and then release

**Comment by halower** [comment]
I'm sorry, I didn't notice this bug before. I misunderstood you, you can install vue-tree-halower@1.3.9, this version has fixed it

**Comment by halower** [comment]
I'm sorry, I didn't notice this bug before. I misunderstood you, you can install vue-tree-halower@1.3.9, this version has fixed it
if you want to use push
```
 chidlrens.forEach( n=> {
        if (!node.hasOwnProperty('children')) {
          this.$set(node, 'children', [])
        }
        node.children.push({n, async: true})
      })
```
or you can use this.$refs.tree.addNodes
