### ISSUE TITLE
Iteration error

### ISSUE THREAD

**Issue by xavierpena** [halower/vue-tree#67]
Apparently, every new node triggers this error:

---

	vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13856 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null"

	found in

	---> <Tree>... (2 recursive calls)
		   <DjdbComponent> at E:\svn-hydrique\DbManager\src\DbManager.OnlineTools\ClientApp\components\djdb\djdb.vue.html
			 <AppComponent> at E:\svn-hydrique\DbManager\src\DbManager.OnlineTools\ClientApp\components\app\app.vue.html
			   <Root>
	warn @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13856
	handleError @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13941
	callHook @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15980
	insert @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16805
	invokeInsertHook @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18633
	patch @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18798
	Vue._update @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15745
	updateComponent @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15861
	get @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16200
	run @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16270
	flushSchedulerQueue @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16037
	(anonymous) @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:14077
	nextTickHandler @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:14024

---

	vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13945 TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
		at VueComponent.initHandle (v2-tree.js:1)
		at VueComponent.boundFn [as initHandle] (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13591)
		at VueComponent.mounted (v2-tree.js:1)
		at callHook (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15978)
		at Object.insert (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16805)
		at invokeInsertHook (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18633)
		at VueComponent.patch [as __patch__] (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18798)
		at VueComponent.Vue._update (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15745)
		at VueComponent.updateComponent (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15861)
		at Watcher.get (vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16200)
	handleError @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:13945
	callHook @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15980
	insert @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16805
	invokeInsertHook @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18633
	patch @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:18798
	Vue._update @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15745
	updateComponent @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:15861
	get @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16200
	run @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16270
	flushSchedulerQueue @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:16037
	(anonymous) @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:14077
	nextTickHandler @ vendor.js?v=MxNIG8b0Wz6QtAfWhyA0-4CCwZshMscBGmtIBXxKshw:14024

**Comment by halower** [comment]
thank you for your feedback. u' problem will be handled within two days.

**Comment by xavierpena** [comment]
Solved: I had to avoid sending the field `children` from the API, which involved dealing with the serialization.

It would be better if the library could deal with `children: null`, because it would give more flexibility on how to send the data from the backend.

**Comment by halower** [comment]
```
        if (!node.hasOwnProperty('children')) {
          this.$set(node, 'children', [])
        }
        node.children.push({title: 'test1', async: true})
```
