### ISSUE TITLE
How can I pass the input response rather than just giving a hard coded json?

### ISSUE THREAD

**Issue by AshKumRaj** [halower/vue-tree#68]
So, I am getting response from a REST api call and storing it in response object like this:

```
callRestService () {
    axios.get('http://localhost:8080/rest/assets')
   .then(response => {
   // JSON responses are automatically parsed.
   this.response = response.data
   })
   .catch(e => {
    this.errors.push(e)
  })
}
```

Then in my template, I have this:
`<v-tree ref='tree' :data='response._embedded.assets' :multiple='true' :tpl='tpl' :halfcheck='true'/>`
But I see the tree structure without any values. Just the + and - signs with checkboxes. This is how my tpl code looks:
```
tpl (node, ctx) {
      let titleClass = node.selected ? 'node-title node-selected' : 'node-title'
      if (node.searched) titleClass += ' node-searched'
      return <span>
        
      <span class={titleClass} domPropsInnerHTML={node.title} onClick={() => {
        ctx.parent.nodeSelected(ctx.props.node)
        console.log(ctx.parent.getSelectedNodes())
      }}></span>
      
      </span>
    }
```
I just need to display the json along with clickable nodes so that I can launch the vue-modal when I click them. I do not need async loading or editing functionality. So I have removed the original demo code. 
Is there any way this can be achieved using this awesome vue-plugin? I do see there is a method called 'node-click'. Any example would be great depicting this.
Thanks.

**Comment by halower** [comment]
Set a property on an object. If the object is reactive, ensure the property is created as a reactive property and trigger view updates. This is primarily used to get around the limitation that Vue cannot detect property additions.

**Comment by AshKumRaj** [comment]
This works. I modified my data inside the response.
