### ISSUE TITLE
min.css is pack with version code can't use in project

### ISSUE THREAD

**Issue by cute-angelia** [halower/vue-tree#69]
![image](https://user-images.githubusercontent.com/26561606/37756686-611d0f02-2de5-11e8-8498-f76f6e7053c8.png)

**Comment by halower** [comment]
has fixed, vue-tree-halower@1.4.0

**Comment by entr** [comment]
I'm still seeing `[data-v-3f867612]` attribute selectors in 1.4.0

**Comment by halower** [comment]
Sorry to be careless when publishing, use scope
