### ISSUE TITLE
运行报错啊

### ISSUE THREAD

**Issue by mmorcc** [halower/vue-tree#76]
output.js:103
Syntax Error: Unexpected token (53:13)
output.js:103
  51 |       let titleClass = node.selected ? 'node-title node-selected' : 'node-title'
  52 |       if (node.searched) titleClass += ' node-searched'
> 53 |       return <span>
     |              ^
  54 |         <button style='color:blue; background-color:pink' onClick={() => this.$refs.tree1.addNode(node, {title: 'sync loading'})}>+</button>
  55 |       <span class={titleClass} domPropsInnerHTML={node.title} onClick={() => {
  56 |         ctx.parent.nodeSelected(ctx.props.node)

**Comment by halower** [comment]
你没有安装第一步所需的库

**Comment by halower** [comment]
需要远程支持，可以留下你的邮箱，晚上我给你看下

**Comment by mmorcc** [comment]
解决了，解决了babelrc配错了,我看了下demo才好了，你这回复很快啊

**Comment by halower** [comment]
为人民服务
