### ISSUE TITLE
Need to add event for check node.

### ISSUE THREAD

**Issue by FrankXie2012** [halower/vue-tree#77]
There is no event for checking node.
node-click is triggerred by clicking node, but when I click the checkbox, the 'node-click' event will not be fired.
I think it's nessesary to add an event for checking node.

**Comment by halower** [comment]
has a event, @nodeChecked

**Comment by halower** [comment]
the```node-check``` event has just been added and the ```nodeChecked``` event has been abandoned in version 1.5.2
