### ISSUE TITLE
 `this.$refs.tree.getNodes({})` does not return any node

### ISSUE THREAD

**Issue by lwolter** [halower/vue-tree#78]
The function `this.$refs.tree.getNodes({})` does not return any node with me since version 1.5.0.
This is probably the cause of my problem with the expansion of the nodes that I reported 3 weeks ago. Excuse the late answer.

**Comment by halower** [comment]
my email is youzisoft@qq.com， you are welcome to complete it.

**Comment by halower** [comment]
well written, I will merge it into the next release

**Comment by halower** [comment]
already merged
