### ISSUE TITLE
不能删除根节点吗？

### ISSUE THREAD

**Issue by xxmi** [halower/vue-tree#79]
this.$refs.tree.delNode(node.parent, node);
node.parent 为 null

**Comment by halower** [comment]
是的，当时我把根节点删除这个功能禁用了，如果需要可以在下次发布时候开放

**Comment by xxmi** [comment]
需要，现在删除根节点只能通过操作 treeData来删除，不是很方便

**Comment by halower** [comment]
你好这个功能已经支持了，请使用最新发布版本，如果确认后请关闭本话题

**Comment by halower** [comment]
长时间没有回复暂时关闭
