### ISSUE TITLE
根节点 async 没有触发

### ISSUE THREAD

**Issue by xxmi** [halower/vue-tree#80]
根节点设置了async 没有触发异步加载，只有第二层的 async 有效，这个是基于什么考虑呢！还是我这边用得不对吗？

**Comment by halower** [comment]
你好，你说的这个问题，可能是我没有考虑周到，下次版本发布会增加这两个功能

**Comment by halower** [comment]
如有疑问你也可以直接给我邮件， youzisoft@qq.com

**Comment by halower** [comment]
你好这个功能已经支持了，请使用最新发布版本，如果确认后请关闭本话题

**Comment by halower** [comment]
长时间没有回复暂时关闭
