### ISSUE TITLE
2000节点时功能已经无法使用

### ISSUE THREAD

**Issue by reece15** [halower/vue-tree#87]
不知道为什么，2000节点时功能已经无法使用，点击所有按钮都会卡好久

**Comment by reece15** [comment]
内存占用从200m上升到600m,点击节点时上升到700M，

**Comment by halower** [comment]
好的，如果你有时间可以一起修复，最近忙别的事情，控件维护可能有点延后

**Comment by halower** [comment]
大概率的问题应该出现在父子节点关系的维护哪里，还有如果这么大的节点为什么不采用异步加载

**Comment by reece15** [comment]
恩，主要是我自己节点有几万个，而且操作时需要选择很多节点，一个一个点开效果不好，得支持搜索，搜索过滤，而且必须有全部展开节点功能，全部展开节点时异步加载不是很好，，，，

**Comment by halower** [comment]
事件处理这块没有使用递归了，展示如果这个卡别的应该会存在同样的问题或者更甚，最有可能的问题就是搜索时状态的变化影响到性能，你有问题，或者修改意见可以直接给我发邮件交流

**Comment by halower** [comment]
主要的代码都在tree.vue那个文件中

**Comment by halower** [comment]
主要的代码都在tree.vue那个文件中

**Comment by halower** [comment]
主要的代码都在tree.vue那个文件中

**Comment by halower** [comment]
已经优化了一下，应该快乐一些，但是你那样一次性加载那么多节点本身应该也有问题哈

**Comment by halower** [comment]
已经优化了一下，应该快乐一些，但是你那样一次性加载那么多节点本身应该也有问题哈

**Comment by reece15** [comment]
客户需求，需要全部展示，jtree优化一下批量事件处理，加上本地缓存，就可以很流畅，最后vue用了iview的tree,也挺流畅
