### ISSUE TITLE
getSelectedNodes doesnt return selected nodes

### ISSUE THREAD

**Issue by nitin-jotwani** [halower/vue-tree#88]
getSelectedNodes returns function instead of an array of selected nodes. Any idea how to work with this?
`this.$refs.tree.getSelectedNodes` returning function

**Comment by halower** [comment]
```this.$refs.tree.getSelectedNodes() ```return  the array of selected tree nodes (removed parent, children and other attributes).  but ``````this.$refs.tree.getSelectedNodes(true) ```return  the array of selected tree nodes(primitive nodes)

**Comment by nitin-jotwani** [comment]
thx! passing true worked.
