### ISSUE TITLE
渲染问题

### ISSUE THREAD

**Issue by Hebingo** [halower/vue-tree#9]
treeData是死数据的时候渲染没问题，可是到动态渲染的时候渲染不出来（确定数据结构一样），但是手动保存一下tree-node.vue之后又可以渲染，但是页面刷新之后又不行了。不懂什么原因。希望大神可以解答一下

**Comment by halower** [comment]
已经修复 https://github.com/halower/vue2-tree/tree/v1.2

**Comment by jingliangwang** [comment]
Module build failed: TypeError: /Users/wangjingliang/Documents/jobs/iris/live/src/components/test/test.vue: Cannot read property 'name' of null
    at /Users/wangjingliang/Documents/jobs/iris/live/node_modules/.0.9.0@babel-plugin-component/lib/core.js:204:33
    at Array.forEach (native)
    at PluginPass.ArrayExpression (/Users/wangjingliang/Documents/jobs/iris/live/node_modules/.0.9.0@babel-plugin-component/lib/core.js:203:20)


我在用的时候 总是报 name  of null 不晓得什么原因
