### ISSUE TITLE
Expand all results on search?

### ISSUE THREAD

**Issue by JohnM-729** [halower/vue-tree#92]
Hi,

First, thanks very much for an immensely useful tree library!
Second, is there any way to expand to all results on search? Or a way to expand/shrink all nodes in a tree?

Thanks!

**Comment by halower** [comment]
all results on search isn't expand ?

**Comment by JohnM-729** [comment]
No - it appears that the first child of the found item is expanded, but not the parents that lead to the found item.

**Comment by halower** [comment]
I am very sorry, I may not understand the meaning of your expression.

**Comment by halower** [comment]
has support
