### ISSUE TITLE
[Feature request] Emit node-expanded event

### ISSUE THREAD

**Issue by tagorecaue** [halower/vue-tree#95]
Please remove comment at this.$emit('node-expanded', node).

**Comment by lour2002** [comment]
@tagorecaue Why?

I need to listen this event.

**Comment by lour2002** [comment]
@halower Please.

I need to listen this event

**Comment by halower** [comment]
releasing a small version the day after tomorrow will support the functionality you need

**Comment by halower** [comment]
well, I'm sorry. actually, it was supported long ago, but the event name is ` async-load-nodes`.
