### ISSUE TITLE
多选模式：为什么父节点选中后子节点没选中？

### ISSUE THREAD

**Issue by Dinrer** [halower/vue-tree#96]
点击父节点名称，父节点复选框被选中，但是父节点下的子节点并没有被选中。望解决！
![image](https://user-images.githubusercontent.com/26219593/43237219-8aa454c8-90bb-11e8-933a-2fcbc44595b5.png)

**Comment by halower** [comment]
你的是什么浏览器，手机和谷歌浏览器正常

**Comment by Dinrer** [comment]
最新版谷歌浏览器，我点击的是节点名称不是复选框
![image](https://user-images.githubusercontent.com/26219593/43245412-c6d22d9c-90e0-11e8-99af-58ed709107d6.png)

**Comment by sgf** [comment]
点节点 而非 复选框 确实有这个问题。

**Comment by halower** [comment]
这个是后期吧节点点击和复选框分离造成的bug，因为当时考虑到样式的一致了， 已经修复
