### ISSUE TITLE
Cannot run the project after installing this plugin...

### ISSUE THREAD

**Issue by litao10422** [halower/vue-tree#97]
I ran the following commands

       vue create project-name
       cd project-name
       npm install vue-tree-halower  --save
       yarn serve

and the following errors are shown

       Failed to compile with 7 errors
       This dependency was not found:
       * vue in ./src/main.js, ./src/router.js and 5 others
       To install it, you can run: npm install --save vue

what's wrong there?

**Comment by halower** [comment]
npm run dev

**Comment by halower** [comment]
npm run dev
