### ISSUE TITLE
多选的逻辑不对

### ISSUE THREAD

**Issue by kymowang** [halower/vue-tree#99]
![sp180809_142114](https://user-images.githubusercontent.com/3396402/43881761-c92ac704-9b9c-11e8-8865-44161dacaf96.png)
如果存在一个 半选的节点，那么这个节点的所有层的父节点都应该是半选，否则的话，从最外面看，所有节点都选择了，其实下面存在没有选择的节点。

**Comment by halower** [comment]
已修复

**Comment by kymowang** [comment]
多谢，我不是专业前端，心有余而力不足啊
